#!/usr/bin/env bash

# Function to display information about a subdomain
display_info() {
    domain="$1"
    subdomain="$2"
    
    # Query DNS records for the subdomain
    output=$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:')
    
    # Extract relevant information using awk
    sub_domain=$(echo "${subdomain}" | awk -F'.' '{print $1}')
    record_type=$(echo "${output}" | awk '/ANSWER SECTION:/{getline; print $4}')
    destination=$(echo "${output}" | awk '/ANSWER SECTION:/{getline; print $5}')
    
    # Output the information
    echo "The subdomain ${sub_domain} is a ${record_type} record and points to ${destination}"
}

# Main script
domain="$1"
subdomain="$2"

if [ -z "${subdomain}" ]; then
    # Display information for default subdomains
    display_info "${domain}" "www"
    display_info "${domain}" "lb-01"
    display_info "${domain}" "web-01"
    display_info "${domain}" "web-02"
else
    # Display information for specified subdomain
    display_info "${domain}" "${subdomain}"
fi
