#!/usr/bin/env bash
# Bash script to configure redirection in Nginx server on Ubuntu
# Redirection must be a “301 Moved Permanently”

# Update package lists and install nginx
apt-get update
apt-get -y install nginx

# Create a simple HTML file containing "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Remove any existing configuration for /redirect_me
sed -i '/location \/redirect_me {/,/}/d' /etc/nginx/sites-available/default

# Define the redirection configuration
redirect_config="location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"

# Add the redirection configuration to the Nginx default site configuration file
sed -i "/server_name _;/a\\
$redirect_config" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
