#!/usr/bin/env bash
# Bash script to configure redirection in Nginx server on Ubuntu
# redirection must be a “301 Moved Permanently”

# Define the redirection configuration
re_direction=$'\\tlocation /redirect_me {\n\\t\treturn 301
https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\\t}\n'

# Update package lists and install nginx
sudo apt-get update
sudo apt-get -y install nginx

# Create a basic HTML page with "Hello World!"
echo "<html><body>Hello World!</body></html>" | sudo tee
/usr/share/nginx/html/index.html

# Add the redirection configuration to the Nginx default site configuration file
sudo sed -i "/listen 80 default_server;/a $re_direction" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

