#!/usr/bin/env bash
# Bash script to configure Nginx server with a custom 404 error page and a 301 redirection

# Update package lists and install nginx
apt-get -y update
apt-get -y install nginx

# Step 1: Return a page with "Holberton School"
echo "Hello World!" > /var/www/html/index.html

# Step 2: Configure a 301 redirection from /redirect_me to a YouTube video
redirect_config="location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sed -i "/server_name _;/a\\
$redirect_config" /etc/nginx/sites-available/default

# Step 3: Configure a custom 404 error page with the message "Ceci n'est pas une page"
echo "Ceci n'est pas une page" > /var/www/html/404.html

custom_404="error_page 404 /404.html;\n
location = /404.html {\n
    internal;\n
}"

sed -i "/server_name _;/a\\
$custom_404" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
