#!/usr/bin/env bash
# Bash script to configure Nginx server with a custom 404 error page and a 301 redirection

# Update package lists and install nginx
apt-get update && apt-get -y install nginx

# Create a simple HTML file containing "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Remove any existing configuration for /redirect_me
sed -i '/location \/redirect_me {/,/}/d' /etc/nginx/sites-available/default

# Define the redirection configuration for /redirect_me
redirect_config="location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}"

# Insert the redirection configuration into the Nginx default site configuration file
sed -i "/server_name _;/a\\
$redirect_config" /etc/nginx/sites-available/default

# Configure a custom 404 error page with the message "Ceci n'est pas une page"
echo "Ceci n'est pas une page" > /var/www/html/404.html

custom_404="error_page 404 /404.html;\n
location = /404.html {\n
    internal;\n
}"

# Insert the custom 404 error page configuration
sed -i "/server_name _;/a\\
$custom_404" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
