#!/usr/bin/env bash
# Configure a new server

# Update package lists
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Start Nginx service
sudo service nginx start

# Get the hostname
HOSTNAME=$(hostname)

# Add custom header to Nginx configuration
sudo sed -i "/http {/a \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

# Create a simple HTML file to serve
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html

# Restart Nginx to apply changes
sudo service nginx restart
