#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

sudo service nginx start
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo service nginx restart
