#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with a sleep 2 in between each iteration,
# and prints "I am invincible!!!" when receiving a SIGTERM signal.

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invicible!!!"' SIGTERM
done
