#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data in the specified format

file="apache-access.log"
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
