#!/usr/bin/env bash
# Script: 100-port_listening_on_localhost
# Description: Listen on port 98 on localhost

# Check if script is run as root
if [[ $(id -u) -ne 0 ]];
then
	echo "Please run this script with sudo or as root."
	exit 1
fi

# Listen on port 98
nc -l 127.0.0.1 98
